Add error messages for `checkNotNull` in the BrokerController
conveyal/r5 pull request #759
Opened 2021-11-15 09:36 UTC by trevorgerhardt

This errors will bubble up to the user so it's useful to have specific error messages and not just "NullPointerException"s.

2021-11-16 14:50 UTC, abyrd requested changes
I'm definitely supportive of adding clearer error messages. In a situation like this I think constant strings are the usual choice, but maybe the best option here is a reusable range checker that ensures they all look like UUIDs and only generates error messages when something looks wrong. I might push another commit to give an example of what I mean.

2021-11-16 15:22 UTC, abyrd commented
I just pushed one commit containing the changes described in my review - this has been tested on normal requests from the UI (which work) and cURL command line requests, which fail when the parameters deviate from UUID or ObjectId format. We'll want to check whether we ever have IDs that don't fit these patterns.

2021-11-18 00:35 UTC, trevorgerhardt commented
Changes look good to me 👍

2021-11-20 01:03 UTC, abyrd approved these changes

2021-11-20 01:03 UTC, merged