Update javadoc to reflect recent LinkageCache changes
conveyal/r5 pull request #947
Opened 2024-10-25 05:20 UTC by abyrd

This is a pure documentation change, fixing some obsolete information I noticed during a recent call.

The final block of documentation in the changeset was changed only for consistency with surrounding comments. It will take longer to work through the open questions in that block and verify current behavior. That would be useful, but I don't think I will reach reliable conclusions on that part by the time we do the release.

2024-10-25 15:44 UTC, ansoncfit requested changes
I made one small suggestion for clarity.

In our recent discussion, I mentioned a vague memory of another comment that might need to be updated, about moving something to a top-level cache. I tried to track this down but didn't find it.

2024-10-25 15:44 UTC, ansoncfit commented on src/main/java/com/conveyal/r5/analyst/LinkageCache.java
> + * in practice since workers are permanently associated with a single TransportNetwork.
```suggestion
 * in practice since workers are permanently associated with a single base TransportNetwork.
```

2024-11-01 04:32 UTC, abyrd commented
>Is the description here still correct?

I think it is still correct, though the way it's phrased might be confusing. When it says "completely bypassing the async loader" it means that while we're still using the async loader class, we're using a method on that class that intentionally skips all the async or background proccessing machinery.

When a regional analysis starts up, we have N tasks all trying to preload at once, and they all block on this method. We don't want N threads performing the slow or heavy calculation steps of preloading redundantly. Nothing in the async loader class itself is causing them to take turns or wait for one preload to finish and share with the other threads. But behind the preloader class there are other caches that do enforce turn-taking and prevent redundant work.

2024-11-01 13:00 UTC, ansoncfit approved these changes
👍

2024-11-01 13:00 UTC, merged